// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPreuQUw9iI5hnIRJ3NdnyEO9TjXoKjcQ',
    appId: '1:295134233109:web:app_id_here',
    messagingSenderId: '295134233109',
    projectId: 'book-swap-92678',
    authDomain: 'book-swap-92678.firebaseapp.com',
    storageBucket: 'book-swap-92678.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPreuQUw9iI5hnIRJ3NdnyEO9TjXoKjcQ',
    appId: '1:295134233109:android:8cc229532a23597690441c',
    messagingSenderId: '295134233109',
    projectId: 'book-swap-92678',
    storageBucket: 'book-swap-92678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB98KZXPjW_eeBnm8sflzKzMQtHcn_dXik',
    appId: '1:295134233109:ios:e282e2f9db61705790441c',
    messagingSenderId: '295134233109',
    projectId: 'book-swap-92678',
    storageBucket: 'book-swap-92678.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB98KZXPjW_eeBnm8sflzKzMQtHcn_dXik',
    appId: '1:295134233109:ios:e282e2f9db61705790441c',
    messagingSenderId: '295134233109',
    projectId: 'book-swap-92678',
    storageBucket: 'book-swap-92678.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );
}
